"""initial_schema

Revision ID: 8757a4254513
Revises: 
Create Date: 2026-05-12 15:25:08.836882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8757a4254513'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('generation_jobs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('total_outfits', sa.Integer(), nullable=True),
    sa.Column('completed_outfits', sa.Integer(), nullable=True),
    sa.Column('failed_outfits', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('outfit_items',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('outfit_image_url', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('prompt_used', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('images_requested', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['generation_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outfit_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outfit_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outfit_items_job_id'), ['job_id'], unique=False)

    op.create_table('generated_images',
    sa.Column('outfit_item_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('consistency_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['outfit_item_id'], ['outfit_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_images_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_images_outfit_item_id'), ['outfit_item_id'], unique=False)

    op.create_table('reference_images',
    sa.Column('outfit_item_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('category', sa.Enum('MODEL', 'BACKGROUND', 'POSE', 'LIGHTING', 'VIBE', 'GENERAL', name='referencecategory'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['outfit_item_id'], ['outfit_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reference_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reference_images_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reference_images_outfit_item_id'), ['outfit_item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reference_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reference_images_outfit_item_id'))
        batch_op.drop_index(batch_op.f('ix_reference_images_id'))

    op.drop_table('reference_images')
    with op.batch_alter_table('generated_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_images_outfit_item_id'))
        batch_op.drop_index(batch_op.f('ix_generated_images_id'))

    op.drop_table('generated_images')
    with op.batch_alter_table('outfit_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outfit_items_job_id'))
        batch_op.drop_index(batch_op.f('ix_outfit_items_id'))

    op.drop_table('outfit_items')
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_generation_jobs_id'))

    op.drop_table('generation_jobs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
